feat(phase1): implement default feature(RemoteRepository, Provider)
cloudforet-io/repository-v2 pull request #2
Opened 2023-02-22 06:10 UTC by GeunjeLEE

### Category
- [X] New feature
- [ ] Bug fix
- [ ] Improvement
- [ ] Refactor
- [ ] etc

### Description
- Implement default feature ([phase 1](https://pyengine.atlassian.net/browse/SPACEONE-157))
  - RemoteRepository(get, list)
  - Provider(create, update, list, get, delete)

### Known issue
- I will merge with squash option, because there are too many commits.  
- Test code has not yet been committed.
  - I will include the test code in the code commit in phase 3.
- Some code for the next phase is shown, but you don't need to review it.

2023-02-22 08:02 UTC, jihyungSong requested changes

2023-02-22 08:02 UTC, jihyungSong commented on src/cloudforet/repository/info/provider_info.py
> +def SyncOptions(sync_options):
If None instead of the structure defined in protobuf 's message , I think it is likely that protobuf will not working it. This is needs to check. 

Below `Schema`, `Capability`, `Description` `Reference` is same case.

2023-02-22 08:58 UTC, GeunjeLEE commented on src/cloudforet/repository/error/remote_repository.py
> +class ERROR_NO_REMOTE_REPOSITORY(ERROR_INVALID_ARGUMENT):
`ERROR_NO_REMOTE_REPOSITORY` means there is no `remote_repository` matching key `name`.
I think, the message `Required parameter.` doesn't seem to fit the above meaning.

Should i rename class name and message?

2023-02-22 09:01 UTC, GeunjeLEE commented on src/cloudforet/repository/info/remote_repository_info.py
> +    info = {
Oh, That nice! 
I should have thought more. 
Thank you.

2023-02-23 01:15 UTC, GeunjeLEE commented on src/cloudforet/repository/info/provider_info.py
> +def SyncOptions(sync_options):
That means, If the request that have 'None' of sync_options(or schema...) is passed from gRPC client, It can be occurred an error?

2023-02-23 02:20 UTC, jihyungSong commented on src/cloudforet/repository/error/remote_repository.py
> +class ERROR_NO_REMOTE_REPOSITORY(ERROR_INVALID_ARGUMENT):
I gave you the wrong answer. 
How about using a class called `ERROR_NOT_FOUND` in core?

```python
class ERROR_NOT_FOUND(ERROR_INVALID_ARGUMENT):
    _message = 'Value not found. ({key} = {value})'
```

I think. this class is fit this situation.

2023-02-23 02:39 UTC, jihyungSong commented on src/cloudforet/repository/info/provider_info.py
> +def SyncOptions(sync_options):
In the case of provider_info, it was worked when replying to the response.
If `SyncOptions` is returned to None in `provider_info`, response may be failed because it is different from what is defined in `provider.proto`.

Below is the link to the file defined in provider.proto

https://github.com/cloudforet-io/api/blob/7ac058d84576285f82127a5d2007fd5b386d245a/proto/spaceone/api/repository/v2/provider.proto#L131

2023-02-23 04:24 UTC, GeunjeLEE commented on src/cloudforet/repository/connector/remote_repository_connector.py
> +    def list_remote_repositories(self, name, version):
Thank you for your comment, i will take this way. 👍

2023-02-23 04:46 UTC, GeunjeLEE commented on src/cloudforet/repository/error/remote_repository.py
> +class ERROR_NO_REMOTE_REPOSITORY(ERROR_INVALID_ARGUMENT):
Cool, I agree that using the ERROR_NOT_FOUND class is enough

2023-02-23 04:57 UTC, GeunjeLEE commented on src/cloudforet/repository/info/provider_info.py
> +def SyncOptions(sync_options):
But, I have written the code that prevents sync_options from being None when provider_info is inserted into the database.

https://github.com/GeunjeLEE/repository-v2/blob/master/src/cloudforet/repository/service/provider_service.py#L78

Should i still check the params?

2023-02-23 08:55 UTC, jihyungSong commented on src/cloudforet/repository/info/provider_info.py
> +def SyncOptions(sync_options):
It's good the code that validate data.
How about to modify sync_options default {} instead of None in Provider model? 

```python
sync_options = EmbeddedDocumentField(SyncOptions, default={})
```

2023-02-23 09:17 UTC, GeunjeLEE commented on src/cloudforet/repository/info/provider_info.py
> +def SyncOptions(sync_options):
It seems good to modify to protect sync_options from being `None` !

I will take this way. Thank you!

2023-02-23 09:28 UTC, GeunjeLEE commented on src/cloudforet/repository/connector/remote_repository_connector.py
> +        if self.remote_repositories:
This feedback has been reflected in the code, resolve conversation.

2023-02-23 09:29 UTC, GeunjeLEE commented on src/cloudforet/repository/connector/remote_repository_connector.py
> +                if name == repository['name']:
This feedback has been reflected in the code, resolve conversation.

2023-02-23 09:29 UTC, GeunjeLEE commented on src/cloudforet/repository/connector/remote_repository_connector.py
> +    def list_remote_repositories(self, name, version):
This feedback has been reflected in the code, resolve conversation.

2023-02-23 09:29 UTC, GeunjeLEE commented on src/cloudforet/repository/info/remote_repository_info.py
> +    info = {
This feedback has been reflected in the code, resolve conversation.

2023-02-23 09:32 UTC, GeunjeLEE commented on src/cloudforet/repository/error/provider.py
> +class ERROR_NO_REMOTE_REPOSITORY(ERROR_INVALID_ARGUMENT):
This feedback has been reflected in the code, resolve conversation.

2023-02-23 09:32 UTC, GeunjeLEE commented on src/cloudforet/repository/error/remote_repository.py
> +class ERROR_NO_REMOTE_REPOSITORY(ERROR_INVALID_ARGUMENT):
This feedback has been reflected in the code, resolve conversation.

2023-02-23 09:33 UTC, GeunjeLEE commented on src/cloudforet/repository/service/remote_repository_service.py
> +    @append_keyword_filter(['name'])
This feedback has been reflected in the code, resolve conversation.

2023-02-23 09:33 UTC, GeunjeLEE commented on src/cloudforet/repository/service/provider_service.py
> +    def update(self, params):
This feedback has been reflected in the code, resolve conversation.

2023-02-23 09:33 UTC, GeunjeLEE commented on src/cloudforet/repository/info/provider_info.py
> +def SyncOptions(sync_options):
This feedback has been reflected in the code, resolve conversation.

2023-02-23 09:37 UTC, GeunjeLEE commented
i've updated code based on feedback
please check again and let me know if there are other problems.

2023-02-23 14:21 UTC, jihyungSong approved these changes
LGTM!

2023-02-23 14:21 UTC, merged